### ISSUE TITLE
Unable to change settings

### ISSUE THREAD

**Issue by ghost** [MarcoPixel/Lano-Visualizer#3] opened 2017-06-25 09:44 UTC
I am unable to change the values in any setting that has the bar.  I assume this is supposed to work as a slider, but it doesn't work at all.  Any setting that uses this input cannot be altered - visualizer scale, song information scale, visualizer height, etc.  

Running Windows 10 Pro 6
4-bit (build 14393) and Rainmeter 4.0.0 r2746 64-bit

![capture](https://user-images.githubusercontent.com/29687463/27515076-51be50ee-5969-11e7-9a8d-a1b18e6e8339.PNG)

**Comment by marcopixel** [comment] 2017-06-25 09:46
Hello!

It seems that the installer for the skin didnt propertly installed all neccessary plugins (as shown in the Chameleon errors). I would recommend reinstalling the visualizer and checking if all plugins are getting installed.

Please report back if that worked.

**Comment by ghost** [comment] 2017-06-25 09:57
It seems I was botching the manual install... d'oh.  I removed it and did the auto install and it works brilliantly.

**Comment by marcopixel** [comment] 2017-06-25 10:07
Great, hope it all works now :)

I'm closing this issue now as the problem is now solved.

**Closed as completed by marcopixel** 2017-06-25 10:07 UTC
