### ISSUE TITLE
Make it transparent desktop wise

### ISSUE THREAD

**Issue by RenatoLopes771** [MarcoPixel/Lano-Visualizer#15] opened 2019-09-01 07:03 UTC
I cant select stuff on the desktop because the app apparently stay in front of the desktop wallper, and its better if it acted transparently (letting me use shortcuts on the desktop).

Also: for some reason it won't detect Spotify song names (even though it visualizes the songs)

**Comment by RenatoLopes771** [comment] 2019-09-02 03:51
OK I'm really stupid. You just enable the checkbox that says "click through" or something like that.

**Comment by DadiBit** [comment] 2020-04-17 11:08
Please close the issue if the problem is fixed.

**Closed as completed** 2020-12-28 02:27 UTC
